### PR TITLE
RAJA/CHAI -> Kripke Integration Testing

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by ajkunen** [comment]
@davidbeckingsale this is great! let me know if there's anything I can do to help

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by ajkunen** [comment]
@davidbeckingsale is this ready for merge, or do you want to do more work on it?

**Comment by davidbeckingsale** [comment]
Up to you - it's currently just testing with one compiler, so I can try and get more enabled in this PR, or we can merge and then add more configurations later.

**Review by ajkunen — APPROVED** [review]
lgtm

**Pull request merged**
