### PR TITLE
Add HIP arch for RZNEVADA.

### PR DESCRIPTION
**Pull request by rchen20**
Need to specify HIP arch on RZNEVADA.

### CODE REVIEW

**Review by rhornung67 — COMMENTED** [review]
rznevada is TOSS$, I believe.

**Comment by rchen20** [comment]
> rznevada is TOSS$, I believe.

Ah right, I'll change that.

**Comment by rhornung67** [comment]
Sorry. I mis-typed. I meant TOSS4.

**Comment by rchen20** [comment]
@vsrana01 Would you mind taking a quick look at this? I've fixed some HIP and Camp issues within Kripke. After this gets merged, I'll create a patch for the last release.

**Review by vsrana01 — APPROVED** [review]

**Pull request merged**
