### PR TITLE
Feature/update raja v0.11.0

### PR DESCRIPTION
**Pull request by mdavis36**
This PR makes the necessary changes to build and run Kripke with RAJA Version 0.11.0

### CODE REVIEW

**Review by rhornung67 — COMMENTED** [review]
@mdavis36 these changes look reasonable to me, but @ajkunen will have to weigh in.

**Comment by mdavis36** [comment]
@ajkunen Could you take a look at this when you get a chance please, thank you.

**Comment by ajkunen** [comment]
@mdavis36 yes!  sorry. I'll get to it shortly.

**Review by ajkunen — APPROVED** [review]
Great!

Thanks for the help!

**Pull request merged**
