### PR TITLE
Update Caliper instrumentation

### PR DESCRIPTION
**Pull request by daboehme**
Update the Caliper instrumentation. Adds main loop instrumentation. Also adds runtime metadata collection with Adiak.

### CODE REVIEW

**Review by brunner6 — COMMENTED** [review]
Should we also update the version of Caliper in the TPLs directory?  Should we add Adiak to the TPLs too?

**Comment by daboehme** [comment]
Hi @brunner6, we're usually building Kripke through spack so we don't use Kripke's TPL submodules. Also, we typically need to set different Caliper CMake options depending on the machine, and doing this through the Kripke CMake script gets rather tedious. In fact I think it would be better to remove Caliper from the TPLs and require it and Adiak to be external libraries.

**Comment by brunner6** [comment]
@daboehme : Normally I agree with external TPLs being the way to go.  But in these vendor benchmark things, we often get push back for using spack, and they want one tarball that does it all.  I'll defer to @aaroncblack and @rchen20 to set the direction this should go.

**Comment by pearce8** [comment]
@brunner6 If you go the submodule route, your team will be on the hook to always update the versions of the dependencies in the git submodules, test each version combination - or help debug the untested state the vendors will end up in.  I would avoid this mess for optional dependencies (which Adiak and Caliper are).

We are working on setting up testing on our end, and looking at performance while at it (which is why we need Adiak and Caliper) - but our testing and interactions with vendors will be limited to Spack builds.

**Review by pearce8 — APPROVED** [review]

**Comment by aaroncblack** [comment]
@pearce8 @brunner6

The approach I recommend is to use externally built libraries, if their locations are provided.  Otherwise fallback on trying to build the libraries via CMake.  Some vendors do push back on spack use, but we can support both.

Example:

if CALIPER_ROOT provided:
 call find_package and use that CALIPER install
else if tpl/caliper directory is present
  build caliper via CMake using the git submodule
else
  throw an error telling developer they either need to provide a caliper installation location, or they need to have the source available in the git submodule location.

(I'd do it for every library like that)

**Comment by pearce8** [comment]
@aaroncblack pointing at TPL installs means you have no control over their versions - and the user may well be the first one to test such a combination of software packages, and therefore to figure out what is broken and why.  This is a terrible software practice for anywhere Mike isn't carrying the brunt of it for the organization.

**Comment by rchen20** [comment]
> Hi @brunner6, we're usually building Kripke through spack so we don't use Kripke's TPL submodules. Also, we typically need to set different Caliper CMake options depending on the machine, and doing this through the Kripke CMake script gets rather tedious. In fact I think it would be better to remove Caliper from the TPLs and require it and Adiak to be external libraries.

@daboehme I'm guessing by this you mean that for every machine configuration, we would need different Caliper and Adiak build parameters (like we have in the Kripke host-configs)?

If so, this is probably best maintained via Spack and/or the Benchpark framework. Will there be public builds of Caliper and Adiak that we can link with? Or is there existing BLT support where commonly used `ENABLE_*` CMake options can be translated to Caliper and Adiak build parameters (e.g. `ENABLE_CUDA=On` activates the Caliper and Adiak CUDA instrumentation without the need for special build params)?

**Comment by brunner6** [comment]
OK.  I'm good with whatever.  If the main route is through spack, then I'll flip my question.  Should we get rid off all the internal TPLs and rely on Spack?  I think having two ways to do things, but only half-supporting one is confusing.

**Comment by daboehme** [comment]
> @daboehme I'm guessing by this you mean that for every machine configuration, we would need different Caliper and Adiak build parameters (like we have in the Kripke host-configs)?

Yes, essentially. That's one of the reasons why it's much easier to have Caliper built with spack.

@brunner6 I think a good middle ground is to make mandatory dependencies like raja available as submodules (but still support providing these externally as well) while optional libraries like Caliper and Adiak must be given as externals by the user. Same as MPI essentially.

**Comment by pearce8** [comment]
@brunner6 I would be curious to know how the team builds and tests Kripke, if it is convenient internally to depend on installed libraries because the team already uses them then perhaps that's a reasonable workflow for your team.

Externally, the main issue with TPLs is that the version for each is left open ended.  The RAJA/chai/etc./BLT suite only works together for very specific versions, and Kripke also needs a specific **set** of them, built a specific way.  This info is not encoded in submodules, and would be hands down better to maintain in a Spack package vs. in the docs and hoping someone can follow those instructions to a T.  Coincidentally, we can **test** the Spack package across many machines using CI which will hopefully reduce the burden on the busy humans.

We took a stab at encoding the current TPL versions for Kripke here:
https://github.com/LLNL/benchpark/blob/develop/repo/kripke/package.py

After this Caliper PR is merged, we will test the Kripke package above across different machines, and come back for approval from your team (ultimately upstreaming the update to the Kripke package to Spack).  The goal is to test this in CI going forward.

**Comment by rchen20** [comment]
> @brunner6 I would be curious to know how the team builds and tests Kripke, if it is convenient internally to depend on installed libraries because the team already uses them then perhaps that's a reasonable workflow for your team.
> 
> Externally, the main issue with TPLs is that the version for each is left open ended. The RAJA/chai/etc./BLT suite only works together for very specific versions, and Kripke also needs a specific **set** of them, built a specific way. This info is not encoded in submodules, and would be hands down better to maintain in a Spack package vs. in the docs and hoping someone can follow those instructions to a T. Coincidentally, we can **test** the Spack package across many machines using CI which will hopefully reduce the burden on the busy humans.
> 
> We took a stab at encoding the current TPL versions for Kripke here: https://github.com/LLNL/benchpark/blob/develop/repo/kripke/package.py
> 
> After this Caliper PR is merged, we will test the Kripke package above across different machines, and come back for approval from your team (ultimately upstreaming the update to the Kripke package to Spack). The goal is to test this in CI going forward.

@pearce8 Kripke is typically built manually from TPL submodules, and builds are updated via the host-config files. It's also tested manually with the standard empty-option run configuration, so this process is not supremely robust.

I'd be happy to have Benchpark CI build and test Kripke regularly, and may even adopt the Caliper/Adiak build parameters into the host-configs.

**Review by rchen20 — APPROVED** [review]

**Pull request merged**
